name: Playwright Firefox CI - Subscriptiontotal Test

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write  # required to push to repo

jobs:
  test-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright and browsers
        run: npx playwright install --with-deps

      - name: Run Subscriptiontotal.spec.js using Firefox
        run: npx playwright test tests/Subscriptiontotal.spec.js --project=firefox --retries=0

      - name: Configure Git (only if test passed)
        if: success()
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Make dummy change (only if test passed)
        if: success()
        run: |
          echo "// Auto-update on $(date -u)" >> tests/Subscriptiontotal.spec.js

      - name: Commit test results or changes (only if test passed)
        if: success()
        run: |
          git add . || echo "Nothing to add"
          git commit -m "Auto-push: Firefox Subscriptiontotal test results" || echo "No changes to commit"

      - name: Push to current branch using PAT (only if test passed)
        if: success()
        env:
          TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          echo "TOKEN length before trimming: ${#TOKEN}"
          TOKEN_CLEAN=$(echo -n "${TOKEN}" | tr -d '[:space:]')
          echo "TOKEN length after trimming: ${#TOKEN_CLEAN}"
          git remote set-url origin "https://x-access-token:${TOKEN_CLEAN}@github.com/${{ github.repository }}.git"
          git push origin HEAD

      - name: Debug Git remotes (optional)
        if: success()
        run: git remote -v
