name: Playwright Test and Update Script

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write

jobs:
  test-and-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run tests (simple test file)
        run: npx playwright test tests/loginp.spec.js --retries=0

      - name: Overwrite test file with full version (only if tests pass)
        if: success()
        run: |
          cat <<EOF > tests/loginp.spec.js
import { test, expect } from '@playwright/test';

test('Verify Subscription display', async ({ page }) => {
    test.setTimeout(90000); // 60 seconds

  await page.goto('https://dev.kredsafe.net/login');
  await page.locator('//input[@name="email"]').fill('swapj@yopmail.com');
  await page.locator('//input[@name="password"]').fill('Nilesh@2025');
  await page.locator('//*[@id="id_frm_submit"]').click();
  await page.goto('https://dev.kredsafe.net/user/subscription/dashboard');
  await page.waitForLoadState('networkidle');

  // Scroll down function
  await page.evaluate(() => window.scrollBy(0, window.innerHeight));

  // Grab the subscription values by selectors
  const subscriptionValue = await page.textContent("span.pill.green");
  console.log("Subscription - " + subscriptionValue.trim());

  const formsPacketValue = await page.textContent("span.pill.yellow");
  console.log("Forms and Packet - " + formsPacketValue.trim());

  const totalValue = await page.textContent("span.pill.red");
  console.log("Total - " + totalValue.trim());
});

// Auto-update on \$(date -u +'%Y-%m-%d')
EOF

      - name: Commit updated test file
        if: success()
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add tests/loginp.spec.js
          git diff --cached --quiet || git commit -m "Update test to full version on $(date -u)"

      - name: Push changes
        if: success()
        env:
          TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}.git
          git push origin HEAD:master
