name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TOKEN: ${{ secrets.PAT_TOKEN }}

    steps:
    - uses: actions/checkout@v3

    - name: Commit and push changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}
        git add .
        git commit -m "Auto commit from workflow" || echo "No changes to commit"
        git push origin HEAD:master
