- name: Configure Git for commit
  if: success()
  run: |
    git config --global user.name "github-actions[bot]"
    git config --global user.email "github-actions[bot]@users.noreply.github.com"

- name: Commit test results
  if: success()
  run: |
    git add -f allure-results/ test-results/ || echo "Nothing to add"
    git commit -m "Auto-push: Subscriptiontotal Firefox test results" || echo "No changes to commit"

- name: Set git remote URL with token
  if: success()
  env:
    PAT: ${{ secrets.PAT_TOKEN }}
  run: |
    git remote set-url origin https://x-access-token:${PAT}@github.com/${{ github.repository }}

- name: Push results to master
  if: success()
  run: |
    git push origin HEAD:master
