name: Playwright Firefox CI - Loginp Test

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write  # required to push to repo

jobs:
  test-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright and browsers
        run: npx playwright install --with-deps

      - name: Run loginp.spec.js using Firefox
        run: npx playwright test tests/loginp.spec.js --project=firefox --retries=0

      - name: Append timestamp to loginp.spec.js (only if test passed)
        if: success()
        run: |
          echo -e "\n// Auto-update on $(date -u)" >> tests/loginp.spec.js

      - name: Show last 10 lines of loginp.spec.js (debug)
        if: success()
        run: tail -n 10 tests/loginp.spec.js

      - name: Check git status and staged diff (debug)
        if: success()
        run: |
          git status
          git diff --cached || echo "No changes staged"

      - name: Commit and push if there are changes
        if: success()
        env:
          TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add tests/loginp.spec.js
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Auto-update timestamp $(date -u)"
            git remote set-url origin "https://x-access-token:${TOKEN}@github.com/${{ github.repository }}.git"
            git push origin HEAD:master
          fi

      - name: Debug Git remotes (optional)
        if: success()
        run: git remote -v
