name: Push to Master

on:
  push:
    branches:
      - main  # or your triggering branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Set remote URL with PAT
        run: |
          CLEAN_PAT=$(echo -n "$PAT_TOKEN")
          git remote set-url origin "https://x-access-token:${CLEAN_PAT}@github.com/nilesh1710/KredSafe.git"

      - name: Push to master
        run: |
          git push origin HEAD: master
