name: Playwright Tests

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('my-playwright-kredsafe/KredSafe/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci
        working-directory: my-playwright-kredsafe/KredSafe

      - name: Install Playwright browsers
        run: npx playwright install --with-deps
        working-directory: my-playwright-kredsafe/KredSafe

      - name: Run Notes.spec.js on Chrome only
        run: npx playwright test tests/Notes.spec.js --project=chrome --reporter=html --config=playwright.config.js
        working-directory: my-playwright-kredsafe/KredSafe

      - name: Upload Playwright HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: my-playwright-kredsafe/KredSafe/playwright-report/
