name: Auto Push Changes

on:
  push:
    branches:
      - master

jobs:
  update-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      # Your script or commands to update files here
      # For example: run tests, generate files, etc.
      - name: Make changes
        run: |
          echo "Auto update" >> update.txt

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --cached --quiet || git commit -m "Auto-push: update files"

      - name: Push changes
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git push https://x-access-token:${PAT_TOKEN}@github.com/nilesh1710/KredSafe.git HEAD:master





