name: Playwright Firefox CI

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Run test in Firefox
        run: npx playwright test tests/Subscriptiontotal.spec.js --project=firefox --retries=0

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit test results
        run: |
          git add -f allure-results/ test-results/ || echo "Nothing to add"
          git commit -m "Auto-push: Firefox test results" || echo "No changes to commit"

      - name: Push to master with PAT
        env:
          TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}
          git push origin HEAD:master
