name: Push to Master

on:
  push:
    branches:
      - main  # Adjust this if your default branch is 'master'

permissions:
  contents: write  # ✅ Required to push code via actions

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Set remote URL with PAT
        run: |
          git remote set-url origin "https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/nilesh1710/KredSafe.git"

      - name: Push to master
        run: |
          git push origin HEAD:master
